/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./../src/components/Layout/Footer/index.vue')['default']
    Header: typeof import('./../src/components/Layout/Header/index.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    Layout: typeof import('./../src/components/Layout/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
  }
}
